### ISSUE TITLE
Using amplify-auth-hooks without amplify-material-ui

### ISSUE THREAD

**Issue by veloware** [hupe1980/amplify-material-ui#13]
I tried - 

```
import {useSignIn} from 'amplify-auth-hooks'
... 
const signIn = useSignIn()
...
const handleSubmit = async () => {
   try {
       const result = await signIn(username, password);
       console.log(result)
   } catch (e) {
       console.log('error', e)
   }
}
```

but get the error -

`Uncaught TypeError: Cannot destructure property 'handleStateChange' of 'useAuthContext(...)' as it is null.`

I had a look through the code, and I think its because I am not using the `withAuthenticator` from the `amplify-material-ui` package, and I dont want to import that as I don't use material-ui.

Any tips on how to use the auth hooks by themselves?

Great package btw

**Comment by hupe1980** [comment]
You need to create your own AuthProvider:
https://github.com/hupe1980/amplify-material-ui/blob/master/packages/amplify-material-ui/src/auth/auth-provider.tsx
