### ISSUE TITLE
Will you accept a migration PR to MUI 5?

### ISSUE THREAD

**Issue by moltar** [hupe1980/amplify-material-ui#49]
We need MUI 5 support, so I am wondering if we shall create a PR that you are willing to merge, or shall we fork?

Cheers!

**Comment by vspdi** [comment]
I actually also ran into this problem. If you would like to provide a PR, that would be awesome.

@hupe1980 Didn´t we already loosely talk about this?

**Comment by moltar** [comment]
> I actually also ran into this problem.

Would you be interested to collab on that?

**Comment by vspdi** [comment]
Yes, did you already start any implementation?

**Comment by moltar** [comment]
We will commence next week (part of the next sprint).

**Comment by hupe1980** [comment]
@haivuw did a great job. I just released a new major release with mui v5 support
